volumes:
  postgres-data:

services:
  progression_db:
    image: postgres
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=24586
        - POSTGRES_DB=LanguageProgression
    volumes:
        -   postgres-data:/var/lib/postgresql/data
    ports:
        - 127.0.0.1:5433:5432

  app:
    restart: always
    build: .
    ports:
      - 8090:8080
    depends_on:
      - progression_db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://progression_db:5432/LanguageProgression"
      JAVA_OPTS: "-Xmx512m"
